queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - label=automerge
    merge_conditions:
      - base~=cosmos/
    commit_message_template: >
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to v0.47.x branch
    conditions:
      - base=cosmos/v0.50.x
      - label=backport/v0.47.x
    actions:
      backport:
        branches:
          - cosmos/v0.47.x
  - name: automerge with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
